/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Flashmoov);
  }
}(this, function(expect, Flashmoov) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Flashmoov.Actor();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Actor', function() {
    it('should create an instance of Actor', function() {
      // uncomment below and update the code to test Actor
      //var instane = new Flashmoov.Actor();
      //expect(instance).to.be.a(Flashmoov.Actor);
    });

    it('should have the property profileType (base name: "profileType")', function() {
      // uncomment below and update the code to test the property profileType
      //var instane = new Flashmoov.Actor();
      //expect(instance).to.be();
    });

    it('should have the property profile (base name: "profile")', function() {
      // uncomment below and update the code to test the property profile
      //var instane = new Flashmoov.Actor();
      //expect(instance).to.be();
    });

    it('should have the property account (base name: "account")', function() {
      // uncomment below and update the code to test the property account
      //var instane = new Flashmoov.Actor();
      //expect(instance).to.be();
    });

    it('should have the property social (base name: "social")', function() {
      // uncomment below and update the code to test the property social
      //var instane = new Flashmoov.Actor();
      //expect(instance).to.be();
    });

  });

}));
