/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Flashmoov);
  }
}(this, function(expect, Flashmoov) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Flashmoov.BlobStoreObject();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BlobStoreObject', function() {
    it('should create an instance of BlobStoreObject', function() {
      // uncomment below and update the code to test BlobStoreObject
      //var instane = new Flashmoov.BlobStoreObject();
      //expect(instance).to.be.a(Flashmoov.BlobStoreObject);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Flashmoov.BlobStoreObject();
      //expect(instance).to.be();
    });

    it('should have the property filename (base name: "filename")', function() {
      // uncomment below and update the code to test the property filename
      //var instane = new Flashmoov.BlobStoreObject();
      //expect(instance).to.be();
    });

    it('should have the property contentType (base name: "contentType")', function() {
      // uncomment below and update the code to test the property contentType
      //var instane = new Flashmoov.BlobStoreObject();
      //expect(instance).to.be();
    });

    it('should have the property chunkSize (base name: "chunkSize")', function() {
      // uncomment below and update the code to test the property chunkSize
      //var instane = new Flashmoov.BlobStoreObject();
      //expect(instance).to.be();
    });

    it('should have the property length (base name: "length")', function() {
      // uncomment below and update the code to test the property length
      //var instane = new Flashmoov.BlobStoreObject();
      //expect(instance).to.be();
    });

    it('should have the property md5 (base name: "md5")', function() {
      // uncomment below and update the code to test the property md5
      //var instane = new Flashmoov.BlobStoreObject();
      //expect(instance).to.be();
    });

    it('should have the property meta (base name: "meta")', function() {
      // uncomment below and update the code to test the property meta
      //var instane = new Flashmoov.BlobStoreObject();
      //expect(instance).to.be();
    });

  });

}));
