/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Flashmoov);
  }
}(this, function(expect, Flashmoov) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Flashmoov.FlashmoovAPIRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FlashmoovAPIRequest', function() {
    it('should create an instance of FlashmoovAPIRequest', function() {
      // uncomment below and update the code to test FlashmoovAPIRequest
      //var instane = new Flashmoov.FlashmoovAPIRequest();
      //expect(instance).to.be.a(Flashmoov.FlashmoovAPIRequest);
    });

    it('should have the property storeobjectSuperclassOf (base name: "storeobject-superclass-of")', function() {
      // uncomment below and update the code to test the property storeobjectSuperclassOf
      //var instane = new Flashmoov.FlashmoovAPIRequest();
      //expect(instance).to.be();
    });

    it('should have the property session (base name: "session")', function() {
      // uncomment below and update the code to test the property session
      //var instane = new Flashmoov.FlashmoovAPIRequest();
      //expect(instance).to.be();
    });

    it('should have the property actor (base name: "actor")', function() {
      // uncomment below and update the code to test the property actor
      //var instane = new Flashmoov.FlashmoovAPIRequest();
      //expect(instance).to.be();
    });

    it('should have the property custom (base name: "custom")', function() {
      // uncomment below and update the code to test the property custom
      //var instane = new Flashmoov.FlashmoovAPIRequest();
      //expect(instance).to.be();
    });

    it('should have the property callback (base name: "callback")', function() {
      // uncomment below and update the code to test the property callback
      //var instane = new Flashmoov.FlashmoovAPIRequest();
      //expect(instance).to.be();
    });

    it('should have the property query (base name: "query")', function() {
      // uncomment below and update the code to test the property query
      //var instane = new Flashmoov.FlashmoovAPIRequest();
      //expect(instance).to.be();
    });

    it('should have the property autocomplete (base name: "autocomplete")', function() {
      // uncomment below and update the code to test the property autocomplete
      //var instane = new Flashmoov.FlashmoovAPIRequest();
      //expect(instance).to.be();
    });

  });

}));
