/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FlashInitBody', 'model/FlashmoovAPIResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/FlashInitBody'), require('../model/FlashmoovAPIResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.RegisterApi = factory(root.Flashmoov.ApiClient, root.Flashmoov.FlashInitBody, root.Flashmoov.FlashmoovAPIResponse);
  }
}(this, function(ApiClient, FlashInitBody, FlashmoovAPIResponse) {
  'use strict';

  /**
   * Register service.
   * @module api/RegisterApi
   * @version 2.0.0
   */

  /**
   * Constructs a new RegisterApi. 
   * @alias module:api/RegisterApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the appInitialization operation.
     * @callback module:api/RegisterApi~appInitializationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FlashmoovAPIResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * App initialization
     * App initialization
     * @param {module:model/FlashInitBody} flashInitBody Flash content
     * @param {module:api/RegisterApi~appInitializationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FlashmoovAPIResponse}
     */
    this.appInitialization = function(flashInitBody, callback) {
      var postBody = flashInitBody;

      // verify the required parameter 'flashInitBody' is set
      if (flashInitBody === undefined || flashInitBody === null) {
        throw new Error("Missing the required parameter 'flashInitBody' when calling appInitialization");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['JWT'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = FlashmoovAPIResponse;

      return this.apiClient.callApi(
        '/flash/init', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
