/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FlashAutocompleteBody', 'model/FlashPromoteBody', 'model/FlashQueryBody', 'model/FlashRecommandedBody', 'model/FlashmoovAPIResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/FlashAutocompleteBody'), require('../model/FlashPromoteBody'), require('../model/FlashQueryBody'), require('../model/FlashRecommandedBody'), require('../model/FlashmoovAPIResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.RetrieveApi = factory(root.Flashmoov.ApiClient, root.Flashmoov.FlashAutocompleteBody, root.Flashmoov.FlashPromoteBody, root.Flashmoov.FlashQueryBody, root.Flashmoov.FlashRecommandedBody, root.Flashmoov.FlashmoovAPIResponse);
  }
}(this, function(ApiClient, FlashAutocompleteBody, FlashPromoteBody, FlashQueryBody, FlashRecommandedBody, FlashmoovAPIResponse) {
  'use strict';

  /**
   * Retrieve service.
   * @module api/RetrieveApi
   * @version 2.0.0
   */

  /**
   * Constructs a new RetrieveApi. 
   * @alias module:api/RetrieveApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the flashAutocomplete operation.
     * @callback module:api/RetrieveApi~flashAutocompleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FlashmoovAPIResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new product
     * Create a new product
     * @param {Object} opts Optional parameters
     * @param {module:model/FlashAutocompleteBody} opts.flashAutocompleteBody 
     * @param {module:api/RetrieveApi~flashAutocompleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FlashmoovAPIResponse}
     */
    this.flashAutocomplete = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['flashAutocompleteBody'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['JWT'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = FlashmoovAPIResponse;

      return this.apiClient.callApi(
        '/flash/autocomplete', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the flashPromoted operation.
     * @callback module:api/RetrieveApi~flashPromotedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FlashmoovAPIResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get products
     * Get products
     * @param {module:model/FlashPromoteBody} flashPromoteBody more book information
     * @param {module:api/RetrieveApi~flashPromotedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FlashmoovAPIResponse}
     */
    this.flashPromoted = function(flashPromoteBody, callback) {
      var postBody = flashPromoteBody;

      // verify the required parameter 'flashPromoteBody' is set
      if (flashPromoteBody === undefined || flashPromoteBody === null) {
        throw new Error("Missing the required parameter 'flashPromoteBody' when calling flashPromoted");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['JWT'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = FlashmoovAPIResponse;

      return this.apiClient.callApi(
        '/flash/promoted', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the flashQuery operation.
     * @callback module:api/RetrieveApi~flashQueryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FlashmoovAPIResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get products
     * Get products
     * @param {module:model/FlashQueryBody} flashQueryBody more book information
     * @param {module:api/RetrieveApi~flashQueryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FlashmoovAPIResponse}
     */
    this.flashQuery = function(flashQueryBody, callback) {
      var postBody = flashQueryBody;

      // verify the required parameter 'flashQueryBody' is set
      if (flashQueryBody === undefined || flashQueryBody === null) {
        throw new Error("Missing the required parameter 'flashQueryBody' when calling flashQuery");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['JWT'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = FlashmoovAPIResponse;

      return this.apiClient.callApi(
        '/flash/query', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the flashRecommanded operation.
     * @callback module:api/RetrieveApi~flashRecommandedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FlashmoovAPIResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get products
     * Get products
     * @param {module:model/FlashRecommandedBody} flashRecommandedBody more book information
     * @param {module:api/RetrieveApi~flashRecommandedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FlashmoovAPIResponse}
     */
    this.flashRecommanded = function(flashRecommandedBody, callback) {
      var postBody = flashRecommandedBody;

      // verify the required parameter 'flashRecommandedBody' is set
      if (flashRecommandedBody === undefined || flashRecommandedBody === null) {
        throw new Error("Missing the required parameter 'flashRecommandedBody' when calling flashRecommanded");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['JWT'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = FlashmoovAPIResponse;

      return this.apiClient.callApi(
        '/flash/recommanded', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
