/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ActorAccount', 'model/ActorEnum', 'model/ActorProfile', 'model/Meta', 'model/SocialProfile', 'model/StoreObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ActorAccount'), require('./ActorEnum'), require('./ActorProfile'), require('./Meta'), require('./SocialProfile'), require('./StoreObject'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.Actor = factory(root.Flashmoov.ApiClient, root.Flashmoov.ActorAccount, root.Flashmoov.ActorEnum, root.Flashmoov.ActorProfile, root.Flashmoov.Meta, root.Flashmoov.SocialProfile, root.Flashmoov.StoreObject);
  }
}(this, function(ApiClient, ActorAccount, ActorEnum, ActorProfile, Meta, SocialProfile, StoreObject) {
  'use strict';




  /**
   * The Actor model module.
   * @module model/Actor
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Actor</code>.
   * @alias module:model/Actor
   * @class
   * @extends module:model/StoreObject
   * @param traitSuperclassOf {module:model/Trait.TraitSuperclassOfEnum} 
   */
  var exports = function(traitSuperclassOf) {
    var _this = this;
    StoreObject.call(_this, traitSuperclassOf);




  };

  /**
   * Constructs a <code>Actor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Actor} obj Optional instance to populate.
   * @return {module:model/Actor} The populated <code>Actor</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      StoreObject.constructFromObject(data, obj);
      if (data.hasOwnProperty('profileType')) {
        obj['profileType'] = ActorEnum.constructFromObject(data['profileType']);
      }
      if (data.hasOwnProperty('profile')) {
        obj['profile'] = ActorProfile.constructFromObject(data['profile']);
      }
      if (data.hasOwnProperty('account')) {
        obj['account'] = ActorAccount.constructFromObject(data['account']);
      }
      if (data.hasOwnProperty('social')) {
        obj['social'] = SocialProfile.constructFromObject(data['social']);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(StoreObject.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {module:model/ActorEnum} profileType
   */
  exports.prototype['profileType'] = undefined;
  /**
   * @member {module:model/ActorProfile} profile
   */
  exports.prototype['profile'] = undefined;
  /**
   * @member {module:model/ActorAccount} account
   */
  exports.prototype['account'] = undefined;
  /**
   * @member {module:model/SocialProfile} social
   */
  exports.prototype['social'] = undefined;



  return exports;
}));


