/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DateAndTime'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DateAndTime'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.DateTimeInterval = factory(root.Flashmoov.ApiClient, root.Flashmoov.DateAndTime);
  }
}(this, function(ApiClient, DateAndTime) {
  'use strict';




  /**
   * The DateTimeInterval model module.
   * @module model/DateTimeInterval
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>DateTimeInterval</code>.
   * @alias module:model/DateTimeInterval
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>DateTimeInterval</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DateTimeInterval} obj Optional instance to populate.
   * @return {module:model/DateTimeInterval} The populated <code>DateTimeInterval</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('start')) {
        obj['start'] = DateAndTime.constructFromObject(data['start']);
      }
      if (data.hasOwnProperty('end')) {
        obj['end'] = DateAndTime.constructFromObject(data['end']);
      }
      if (data.hasOwnProperty('iso')) {
        obj['iso'] = ApiClient.convertToType(data['iso'], 'String');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DateAndTime} start
   */
  exports.prototype['start'] = undefined;
  /**
   * @member {module:model/DateAndTime} end
   */
  exports.prototype['end'] = undefined;
  /**
   * @member {String} iso
   */
  exports.prototype['iso'] = undefined;
  /**
   * Duration in minute
   * @member {Number} duration
   */
  exports.prototype['duration'] = undefined;



  return exports;
}));


