/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MongoConfiguration'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MongoConfiguration'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.EnvironmentConfiguration = factory(root.Flashmoov.ApiClient, root.Flashmoov.MongoConfiguration);
  }
}(this, function(ApiClient, MongoConfiguration) {
  'use strict';




  /**
   * The EnvironmentConfiguration model module.
   * @module model/EnvironmentConfiguration
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>EnvironmentConfiguration</code>.
   * @alias module:model/EnvironmentConfiguration
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>EnvironmentConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EnvironmentConfiguration} obj Optional instance to populate.
   * @return {module:model/EnvironmentConfiguration} The populated <code>EnvironmentConfiguration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('mongoDatasource')) {
        obj['mongoDatasource'] = ApiClient.convertToType(data['mongoDatasource'], [MongoConfiguration]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/MongoConfiguration>} mongoDatasource
   */
  exports.prototype['mongoDatasource'] = undefined;



  return exports;
}));


