/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.FacebookConfiguration = factory(root.Flashmoov.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FacebookConfiguration model module.
   * @module model/FacebookConfiguration
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>FacebookConfiguration</code>.
   * @alias module:model/FacebookConfiguration
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>FacebookConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FacebookConfiguration} obj Optional instance to populate.
   * @return {module:model/FacebookConfiguration} The populated <code>FacebookConfiguration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('applicationKey')) {
        obj['applicationKey'] = ApiClient.convertToType(data['applicationKey'], 'String');
      }
      if (data.hasOwnProperty('applicationSecret')) {
        obj['applicationSecret'] = ApiClient.convertToType(data['applicationSecret'], 'String');
      }
      if (data.hasOwnProperty('flashmoovPageId')) {
        obj['flashmoovPageId'] = ApiClient.convertToType(data['flashmoovPageId'], 'String');
      }
      if (data.hasOwnProperty('flashmoovAccessToken')) {
        obj['flashmoovAccessToken'] = ApiClient.convertToType(data['flashmoovAccessToken'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} applicationKey
   */
  exports.prototype['applicationKey'] = undefined;
  /**
   * @member {String} applicationSecret
   */
  exports.prototype['applicationSecret'] = undefined;
  /**
   * @member {String} flashmoovPageId
   */
  exports.prototype['flashmoovPageId'] = undefined;
  /**
   * @member {String} flashmoovAccessToken
   */
  exports.prototype['flashmoovAccessToken'] = undefined;



  return exports;
}));


