/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Actor', 'model/Flash', 'model/FlashmoovAPIRequest', 'model/Query'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Actor'), require('./Flash'), require('./FlashmoovAPIRequest'), require('./Query'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.FlashBodyRequest = factory(root.Flashmoov.ApiClient, root.Flashmoov.Actor, root.Flashmoov.Flash, root.Flashmoov.FlashmoovAPIRequest, root.Flashmoov.Query);
  }
}(this, function(ApiClient, Actor, Flash, FlashmoovAPIRequest, Query) {
  'use strict';




  /**
   * The FlashBodyRequest model module.
   * @module model/FlashBodyRequest
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>FlashBodyRequest</code>.
   * @alias module:model/FlashBodyRequest
   * @class
   * @extends module:model/FlashmoovAPIRequest
   */
  var exports = function() {
    var _this = this;
    FlashmoovAPIRequest.call(_this);

  };

  /**
   * Constructs a <code>FlashBodyRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FlashBodyRequest} obj Optional instance to populate.
   * @return {module:model/FlashBodyRequest} The populated <code>FlashBodyRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      FlashmoovAPIRequest.constructFromObject(data, obj);
      if (data.hasOwnProperty('body')) {
        obj['body'] = Flash.constructFromObject(data['body']);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(FlashmoovAPIRequest.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {module:model/Flash} body
   */
  exports.prototype['body'] = undefined;



  return exports;
}));


