/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Actor', 'model/Query'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Actor'), require('./Query'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.FlashmoovAPIRequest = factory(root.Flashmoov.ApiClient, root.Flashmoov.Actor, root.Flashmoov.Query);
  }
}(this, function(ApiClient, Actor, Query) {
  'use strict';




  /**
   * The FlashmoovAPIRequest model module.
   * @module model/FlashmoovAPIRequest
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>FlashmoovAPIRequest</code>.
   * @alias module:model/FlashmoovAPIRequest
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>FlashmoovAPIRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FlashmoovAPIRequest} obj Optional instance to populate.
   * @return {module:model/FlashmoovAPIRequest} The populated <code>FlashmoovAPIRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('storeobject-superclass-of')) {
        obj['storeobject-superclass-of'] = ApiClient.convertToType(data['storeobject-superclass-of'], 'String');
      }
      if (data.hasOwnProperty('session')) {
        obj['session'] = ApiClient.convertToType(data['session'], Object);
      }
      if (data.hasOwnProperty('actor')) {
        obj['actor'] = Actor.constructFromObject(data['actor']);
      }
      if (data.hasOwnProperty('custom')) {
        obj['custom'] = ApiClient.convertToType(data['custom'], Object);
      }
      if (data.hasOwnProperty('callback')) {
        obj['callback'] = ApiClient.convertToType(data['callback'], 'String');
      }
      if (data.hasOwnProperty('query')) {
        obj['query'] = Query.constructFromObject(data['query']);
      }
      if (data.hasOwnProperty('autocomplete')) {
        obj['autocomplete'] = ApiClient.convertToType(data['autocomplete'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/FlashmoovAPIRequest.StoreobjectSuperclassOfEnum} storeobject-superclass-of
   */
  exports.prototype['storeobject-superclass-of'] = undefined;
  /**
   * @member {Object} session
   */
  exports.prototype['session'] = undefined;
  /**
   * @member {module:model/Actor} actor
   */
  exports.prototype['actor'] = undefined;
  /**
   * @member {Object} custom
   */
  exports.prototype['custom'] = undefined;
  /**
   * @member {String} callback
   */
  exports.prototype['callback'] = undefined;
  /**
   * @member {module:model/Query} query
   */
  exports.prototype['query'] = undefined;
  /**
   * @member {String} autocomplete
   */
  exports.prototype['autocomplete'] = undefined;


  /**
   * Allowed values for the <code>storeobject-superclass-of</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StoreobjectSuperclassOfEnum = {
    /**
     * value: "FlashBodyRequest"
     * @const
     */
    "FlashBodyRequest": "FlashBodyRequest"  };


  return exports;
}));


