/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FlashPolicies', 'model/FlashVisibilityEnum'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FlashPolicies'), require('./FlashVisibilityEnum'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.FlashCard = factory(root.Flashmoov.ApiClient, root.Flashmoov.FlashPolicies, root.Flashmoov.FlashVisibilityEnum);
  }
}(this, function(ApiClient, FlashPolicies, FlashVisibilityEnum) {
  'use strict';




  /**
   * The FlashCard model module.
   * @module model/FlashCard
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>FlashCard</code>.
   * @alias module:model/FlashCard
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>FlashCard</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FlashCard} obj Optional instance to populate.
   * @return {module:model/FlashCard} The populated <code>FlashCard</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('uri')) {
        obj['uri'] = ApiClient.convertToType(data['uri'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('language')) {
        obj['language'] = ApiClient.convertToType(data['language'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = FlashVisibilityEnum.constructFromObject(data['status']);
      }
      if (data.hasOwnProperty('policies')) {
        obj['policies'] = FlashPolicies.constructFromObject(data['policies']);
      }
    }
    return obj;
  }

  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} uri
   */
  exports.prototype['uri'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} language
   */
  exports.prototype['language'] = undefined;
  /**
   * @member {module:model/FlashVisibilityEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {module:model/FlashPolicies} policies
   */
  exports.prototype['policies'] = undefined;



  return exports;
}));


