/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FlashContentTypeEnum'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FlashContentTypeEnum'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.FlashContent = factory(root.Flashmoov.ApiClient, root.Flashmoov.FlashContentTypeEnum);
  }
}(this, function(ApiClient, FlashContentTypeEnum) {
  'use strict';




  /**
   * The FlashContent model module.
   * @module model/FlashContent
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>FlashContent</code>.
   * @alias module:model/FlashContent
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>FlashContent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FlashContent} obj Optional instance to populate.
   * @return {module:model/FlashContent} The populated <code>FlashContent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('content-type')) {
        obj['content-type'] = FlashContentTypeEnum.constructFromObject(data['content-type']);
      }
      if (data.hasOwnProperty('uri')) {
        obj['uri'] = ApiClient.convertToType(data['uri'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/FlashContentTypeEnum} content-type
   */
  exports.prototype['content-type'] = undefined;
  /**
   * @member {String} uri
   */
  exports.prototype['uri'] = undefined;
  /**
   * @member {String} message
   */
  exports.prototype['message'] = undefined;



  return exports;
}));


