/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FlashPermission'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FlashPermission'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.FlashPolicies = factory(root.Flashmoov.ApiClient, root.Flashmoov.FlashPermission);
  }
}(this, function(ApiClient, FlashPermission) {
  'use strict';




  /**
   * The FlashPolicies model module.
   * @module model/FlashPolicies
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>FlashPolicies</code>.
   * @alias module:model/FlashPolicies
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>FlashPolicies</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FlashPolicies} obj Optional instance to populate.
   * @return {module:model/FlashPolicies} The populated <code>FlashPolicies</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('readable')) {
        obj['readable'] = FlashPermission.constructFromObject(data['readable']);
      }
      if (data.hasOwnProperty('writable')) {
        obj['writable'] = FlashPermission.constructFromObject(data['writable']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/FlashPermission} readable
   */
  exports.prototype['readable'] = undefined;
  /**
   * @member {module:model/FlashPermission} writable
   */
  exports.prototype['writable'] = undefined;



  return exports;
}));


