/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Actor', 'model/Props', 'model/Tags'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Actor'), require('./Props'), require('./Tags'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.Meta = factory(root.Flashmoov.ApiClient, root.Flashmoov.Actor, root.Flashmoov.Props, root.Flashmoov.Tags);
  }
}(this, function(ApiClient, Actor, Props, Tags) {
  'use strict';




  /**
   * The Meta model module.
   * @module model/Meta
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Meta</code>.
   * @alias module:model/Meta
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>Meta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Meta} obj Optional instance to populate.
   * @return {module:model/Meta} The populated <code>Meta</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('creator')) {
        obj['creator'] = Actor.constructFromObject(data['creator']);
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'Number');
      }
      if (data.hasOwnProperty('updated')) {
        obj['updated'] = ApiClient.convertToType(data['updated'], 'Number');
      }
      if (data.hasOwnProperty('props')) {
        obj['props'] = Props.constructFromObject(data['props']);
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = Tags.constructFromObject(data['tags']);
      }
      if (data.hasOwnProperty('autocomplete')) {
        obj['autocomplete'] = ApiClient.convertToType(data['autocomplete'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Actor} creator
   */
  exports.prototype['creator'] = undefined;
  /**
   * @member {Number} created
   */
  exports.prototype['created'] = undefined;
  /**
   * @member {Number} updated
   */
  exports.prototype['updated'] = undefined;
  /**
   * @member {module:model/Props} props
   */
  exports.prototype['props'] = undefined;
  /**
   * @member {module:model/Tags} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * @member {String} autocomplete
   */
  exports.prototype['autocomplete'] = undefined;



  return exports;
}));


