/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MongoConfigurationInner'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MongoConfigurationInner'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.MongoConfiguration = factory(root.Flashmoov.ApiClient, root.Flashmoov.MongoConfigurationInner);
  }
}(this, function(ApiClient, MongoConfigurationInner) {
  'use strict';




  /**
   * The MongoConfiguration model module.
   * @module model/MongoConfiguration
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>MongoConfiguration</code>.
   * @alias module:model/MongoConfiguration
   * @class
   * @extends Array
   */
  var exports = function() {
    var _this = this;
    _this = new Array();
    Object.setPrototypeOf(_this, exports);

    return _this;
  };

  /**
   * Constructs a <code>MongoConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MongoConfiguration} obj Optional instance to populate.
   * @return {module:model/MongoConfiguration} The populated <code>MongoConfiguration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'MongoConfigurationInner');

    }
    return obj;
  }




  return exports;
}));


