/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/QueryPrj', 'model/QuerySort'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./QueryPrj'), require('./QuerySort'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.Query = factory(root.Flashmoov.ApiClient, root.Flashmoov.QueryPrj, root.Flashmoov.QuerySort);
  }
}(this, function(ApiClient, QueryPrj, QuerySort) {
  'use strict';




  /**
   * The Query model module.
   * @module model/Query
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Query</code>.
   * @alias module:model/Query
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Query</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Query} obj Optional instance to populate.
   * @return {module:model/Query} The populated <code>Query</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('query')) {
        obj['query'] = ApiClient.convertToType(data['query'], Object);
      }
      if (data.hasOwnProperty('prj')) {
        obj['prj'] = QueryPrj.constructFromObject(data['prj']);
      }
      if (data.hasOwnProperty('sort')) {
        obj['sort'] = QuerySort.constructFromObject(data['sort']);
      }
      if (data.hasOwnProperty('skip')) {
        obj['skip'] = ApiClient.convertToType(data['skip'], 'Number');
      }
      if (data.hasOwnProperty('limit')) {
        obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Object} query
   */
  exports.prototype['query'] = undefined;
  /**
   * @member {module:model/QueryPrj} prj
   */
  exports.prototype['prj'] = undefined;
  /**
   * @member {module:model/QuerySort} sort
   */
  exports.prototype['sort'] = undefined;
  /**
   * @member {Number} skip
   */
  exports.prototype['skip'] = undefined;
  /**
   * @member {Number} limit
   */
  exports.prototype['limit'] = undefined;



  return exports;
}));


