/**
 * Flashmoov
 * Flashmoov
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@flashmoov.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Meta', 'model/StoreObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Meta'), require('./StoreObject'));
  } else {
    // Browser globals (root is window)
    if (!root.Flashmoov) {
      root.Flashmoov = {};
    }
    root.Flashmoov.SessionTemp = factory(root.Flashmoov.ApiClient, root.Flashmoov.Meta, root.Flashmoov.StoreObject);
  }
}(this, function(ApiClient, Meta, StoreObject) {
  'use strict';




  /**
   * The SessionTemp model module.
   * @module model/SessionTemp
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>SessionTemp</code>.
   * @alias module:model/SessionTemp
   * @class
   * @extends module:model/StoreObject
   * @param traitSuperclassOf {module:model/Trait.TraitSuperclassOfEnum} 
   */
  var exports = function(traitSuperclassOf) {
    var _this = this;
    StoreObject.call(_this, traitSuperclassOf);
  };

  /**
   * Constructs a <code>SessionTemp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SessionTemp} obj Optional instance to populate.
   * @return {module:model/SessionTemp} The populated <code>SessionTemp</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      StoreObject.constructFromObject(data, obj);
    }
    return obj;
  }

  exports.prototype = Object.create(StoreObject.prototype);
  exports.prototype.constructor = exports;




  return exports;
}));


